#
# $Id: Makefile,v 1.1 1993-12-10 01:15:29 caraher Exp $
#
# Author:
#  P.J. Caraher 1/26/93
#
# Description:
#  Makefile for the SGP maps directory
#
# $Log: not supported by cvs2svn $
#
#
 
MFVERSION = "$Id: Makefile,v 1.1 1993-12-10 01:15:29 caraher Exp $"

FILES = state_lines.map

install: 
	install -c $(FILES) $(BINHOME)/../SGP/maps

release: 
	install -c $(FILES) $(DISTBIN)/../SGP/maps

Makefile:
