#
# $Id: Makefile,v 1.2 2008-04-16 18:26:54 granger Exp $
#
# Author:
#  P.J. Caraher 1/26/93
#
# Description:
#  Makefile for the SGP maps directory
#
 
MFVERSION = "$Id: Makefile,v 1.2 2008-04-16 18:26:54 granger Exp $"

FILES = state_lines.map

install: 
	install -c $(FILES) $(BINHOME)/../SGP/maps

release: 
	install -c $(FILES) $(DISTBIN)/../SGP/maps

Makefile:
