#!/bin/csh -f
#
# Start up the Zeb system.
#
# Do everything possible to insure that we start clean.
#
        setenv XAPPLRESDIR ${ZEBHOME}/lib/resources
        setenv ZEB_TOPDIR ${ZEBHOME}
	setenv ZEB_PROJECT $CONFIGHOME
        setenv NO_DM_TIME yes
        setenv HOST `uname -n`
        cd $CONFIGHOME
        sleep 1
#       set nonomatch; rm -f ${ZEBHOME}/tmp/*
	$BINHOME/tweakcolor yellow
#
# Start the display manager.
#
	setenv DEFAULT_CONFIG empty
#	xgdb $BINHOME/dm 
	exec $BINHOME/dm  $CONFIGHOME/dm.config
