#!/bin/csh -f
# 
# Start up the Zeb system.
#
# Do everything possible to insure that we start clean.
#
	setenv NO_DM_TIME no
	setenv HOST `uname -n`
	setenv ZEB_TOPDIR $ZEBHOME
	setenv ZEB_PROJECT $CONFIGHOME
	setenv XAPPLRESDIR ${ZEB_TOPDIR}/lib/resources
	cd $CONFIGHOME
	$BINHOME/zstop
	if ( $?ZEB_SOCKET ) then
		rm -f $ZEB_SOCKET
	else
		rm -f /tmp/fcc.socket
	endif
	sleep 1
#	set nonomatch; rm -f ${ZEBHOME}/tmp/*
#
# The message system.  Nothing else runs without it.
#
	echo 'Starting MESSAGE...'
	$BINHOME/message
	sleep 1
#
# Wait until message is truly ready.  
#
#	$BINHOME/mstatus > /dev/null
#
# The event logger.
#
#setenv EVENT_MASK 31
	echo -n 'Starting the event logger...'
	$BINHOME/EventLogger -w &
	sleep 1
#
# Start the timer.
#
	echo -n 'Starting the timer...'
	$BINHOME/timer &
#
# Data store processes.
#
	echo -n '...and the data store daemon...'
	$BINHOME/dsDaemon $CONFIGHOME/ds.config &
	sleep 1
