#! /bin/sh
#
# $Id: makeall,v 1.4 1999-03-01 23:46:34 granger Exp $
#
# Generate all the template configs in this directory

perl=perl
$perl ./tmake '' iss-batch iss1 iss2 iss3 iss4
$perl ./tmake 'lineplot-' template iss1 iss2 iss3 iss4
$perl ./tmake 'class-' template bel bea alg tim own sud

