#! /bin/sh
#
# $Id: makeall,v 1.1 1997-12-16 22:55:47 granger Exp $
#
# Generate all the template configs in this directory

./tmake iss-batch '' iss1 iss2 iss3
./tmake lineplot-template 'lineplot-' iss1 iss2 iss3
./tmake class-template 'class-' bel bea alg tim own sud

