#! /bin/sh

# This must be run with nohup to run in the background, because it seems
# svn2git expects to write progress to a tty:
#
# nohup ./zebra-to-git &> zebra-to-git.log 2>&1 &

# This depends on a complete authors file in ~/.svn2git/authors

set -x

base=`pwd`

svnfast=/home/granger/code/svn2git/svn-all-fast-export

# svn2git final gc can fail for some reason, so do it manually and keep
# the script going


run_svn_fast() {
    rm -rf zebra-extra.git
    $svnfast --svn-ignore --add-metadata --identity-map ~/.svn2git/authors --rules zebra-doc.rules /home/granger/code/svn-repo/rdss >& svn2git.log
}


run_svn2git() {
    mkdir zebra-doc
    cd zebra-doc
    svn2git --metadata file:///home/granger/code/svn-repo/rdss --trunk trunk/zebra --exclude source/  --nobranches --notags || git gc
    cd ..
}


run_svn_fast
