#
# $Id: Makefile,v 1.4 2008-04-16 18:26:54 granger Exp $
#
# Author:
#  P.J. Caraher 1/26/93
#
 
MFVERSION = "$Id: Makefile,v 1.4 2008-04-16 18:26:54 granger Exp $"

FILES = defaults.pd instrument.pd instrument2.pd instrument3.pd instrument4.pd \
	instrument5.pd kansas.pd mesonet.pd ok_bounds.pd ok_ops-ctr.pd ok_sonde1.pd \
	oklahoma_rivers.pd skewt.pd state_lines.pd whiteclock.pd sounding.pd

install: 
	install -c $(FILES) $(BINHOME)/../SGP/pd

release: 
	install -c $(FILES) $(DISTBIN)/../SGP/pd

Makefile:


