#! /bin/csh -f
#

setenv ZEB_CACHEDIR tmp
setenv DATA_DIR /net/sssf2/cases99
setenv ZEB_PROJDIR /net/sssf2/cases99/cases99-iss

# Any displays started on this project should leave the datastore
# running in the background for other displays and for the plot
# generation.
setenv PRESERVE_ZEB 1

# This project uses its own specific socket
setenv ZEB_SOCKET "/tmp/zebra.cases99-iss"

# The spool dir is where images are dumped by batch-plot
setenv BATCH_IMAGE_SPOOL "/net/www/sssf/projects/cases99/realtime"

# Use a fixed zebra top since we are version-dependent
setenv ZEB_TOPDIR /scr/steam/granger/zebra

# Settings required by ftpplots
setenv PLOT_FTP_HOST "ftp.joss.ucar.edu"
setenv PLOT_FTP_DIR "/pub/incoming/catalog/cases99"
setenv PLOT_FTP_ENABLE 1

# Special paths for Xvfb and zebra.
setenv PATH "$ZEB_TOPDIR/bin:/local/X11R6/bin:$PATH"
if ($?LD_LIBRARY_PATH) then
    setenv LD_LIBRARY_PATH "/local/X11R6/lib:/usr/local/lib:${LD_LIBRARY_PATH}"
else
    setenv LD_LIBRARY_PATH "/local/X11R6/lib:/usr/local/lib"
endif

# zplotd parameters
setenv IMAGE_MAIL_LIST " granger "
setenv PLOT_PLATFORMS "$ZEB_PROJDIR/Plots"



