#!/bin/tcsh
#
# Set up environment
#
setenv DEFAULT_DATA_DIR /data/bamex

if (! $?DATA_DIR) setenv DATA_DIR $DEFAULT_DATA_DIR
if (! $?ZEB_EVENTLOGGER) \
    setenv ZEB_EVENTLOGGER "$ZEB_TOPDIR/bin/EventLogger -w"
if (! $?DEFAULT_CONFIG) setenv DEFAULT_CONFIG empty


