#!/bin/csh
# 
# Start up the FCC system.
#
# $Id: raststart,v 1.1.1.1 1995-01-20 05:02:43 granger Exp $
#
cd ../bin
fccstop
rm -f /tmp/fcc.socket
sleep 1

echo -n 'Starting MESSAGE...'
message & 
sleep 1

echo -n 'Starting the event logger...'
EventLogger &
sleep 1

echo -n 'Starting the timer...'
timer &
echo -n '...and the data store daemon...'
dsDaemon ds.config&
sleep 5

echo -n '...The radar data ingest module (put the display widget on the right)'
radar_ingest adrad.params >& radar_ingest.out &

sleep 2
echo -n '...the network data broadcaster...'
#NetXfr Send.mhr &

echo -n 'Finally the display manager.'
dm dm.config&
