#! /bin/sh
#
# Generate batch plots for each iss and send them to JOSS
# $Id: jossplots,v 1.1.1.1 1997-12-04 18:27:38 granger Exp $
#
# Configurations to plot: iss1, iss2, iss3

proj=/net/sssf3/lake_ice/zebra/project/lake_ice
status="ok"

configs='iss1 iss2 iss3'

if [ $# -gt 0 ]; then
    configs="$*"
fi

log=logs/jossplots.`date -u '+%y%m%d.%H%M'`.log
echo "Log file: $log" > $log

for display in $configs; do

	if ./batch-plot now $display >> $log 2>&1; then :; else
		status="FAILED"
	fi

done

images=`./logimages $log`

echo >> $log
ftpjoss.pl $images >> $log 2>&1

elm -s "jossplots $status, log: $log" granger < $log > /dev/null

