#!/bin/csh

onintr finished
set nonomatch

setenv ZEB_SOCKET /tmp/zeb.soundings
setenv DATA_DIR /data/ace1
setenv HOST `uname -n`

/zeb/bin/message

sh << _EOF_
        /zeb/bin/EventLogger -n -m epi -f /tmp/zeb.soundings.log &
        sleep 2
        /zeb/bin/timer &
        sleep 2
        /zeb/bin/dsDaemon /zeb/project/ace1/ds.config 1>/dev/null 2>&1 &
_EOF_

cd /data/incoming/sounding

foreach file (*.raw)
	if ($file == "*.raw") break
	/zeb/project/ace1/ingest/ace-sounding/ace-sounding $file >& /dev/null
	mv $file done/
end

finished:
zstop >& /dev/null

#
# Now do a dsrescan if somebody's running Zebra here right now
#
unsetenv ZEB_SOCKET
if ({ /zeb/bin/mstatus }) /zeb/bin/dsrescan sounding >& /dev/null

