#!/bin/tcsh
#
# Set up environment for SPOL operations.
#
if (! $?DATA_DIR) setenv DATA_DIR /data/spol
if (! $?ZEB_EVENTLOGGER) \
    setenv ZEB_EVENTLOGGER "$ZEB_TOPDIR/bin/EventLogger -w"
if (! $?DEFAULT_CONFIG) setenv DEFAULT_CONFIG empty

