#!/bin/csh
#
# Shell script to reingest GOES data from a given time
#

if ($#argv != 1) then
	echo "Usage: $0 yymmddhhmm"
	exit (1)
endif

set rawdir = "/data/raps/raw_goes"

cat > reingest.ini << _EOF_
	limits 38.8 -106.0 41.3 -103.3
	set platform "goes"
	set originLat 39.88
	set kmResolution 1
	file $rawdir/$1.vis vis
	file $rawdir/$1.ir ir
_EOF_

nice +5 newSatIngest reingest.ini

