#!/bin/csh
#
# The weather project startup file, to be run out of "zstart".  
#

#
# Start the Sound client
#
Sound &

#
# Provide a reasonable default config
#
if ( ! $?DEFAULT_CONFIG ) setenv DEFAULT_CONFIG wind-tseries
