! $Id: cf-active-loc.cpp,v 1.6 1999-04-13 21:56:52 granger Exp $
!
! ------------------------------------------------------------------------
! DO NOT EDIT THIS FILE if it has been installed in the project directory
! tree. This file is generated from a cpp source file in the ./src directory!
! ------------------------------------------------------------------------
!
! Support for active facility locations.
!

!
! Include access to the E13 instruments, since our active area is
! covering E13's active area.
!
require 'ef-active-loc'

!
! Menu for platforms available at a central facility
!
define widget cf-send-menu intmenu 'cf instrument sender'
	title 'Central Facility Instruments'
	line
	submenu '50-MHz RASS' 'rass-50-menu'
	submenu '915-MHz RASS' 'rass-915-menu'
#ifndef UAV
	submenu 'Tower Platforms' 'tower-menu'
	submenu 'BSRN' 'bsrn-menu'
#endif
	submenu 'MFR' 'mfr-menu'
	submenu 'MWR' 'mwr-menu'
	entry 'Sonde (wrpn, a1)' 'cf-sonde-select sgpsondewrpn .a1 pres'
	entry 'Radiation (swrad)' 'cf-select sgpswrad .c1 net_surface_radiation'
	line
	submenu 'E13 Instruments' ef-send-menu	
endmenu


define widget rass-50-menu intmenu 'rass platforms'
	title '50 MHz RASS Profiler'
	line
	entry 'Temperature (a2)' 'cf-select Dsgp50rwptemp .a2 temp'
#ifndef UAV
	entry 'Temperature (a1)' 'cf-select Dsgp50rwptemp .a1 temp'
	entry 'Temperature (a0)' 'cf-select Dsgp50rwptemp .a0 temp'
	entry 'Temperature (b1)' 'cf-select Dsgp50rwptemp .b1 temp'
	line
#endif
	entry 'Wind (a2)' 'cf-select Dsgp50rwpwind .a2 none'
#ifndef UAV
	entry 'Wind (a1)' 'cf-select Dsgp50rwpwind .a1 none'
	entry 'Wind (a0)' 'cf-select Dsgp50rwpwind .a0 none'
	entry 'Wind (b1)' 'cf-select Dsgp50rwpwind .b1 none'
#endif
endmenu
	

define widget rass-915-menu intmenu 'rass platforms'
	title '915 MHz RASS Profiler'
	line
	entry 'Temperature (a2)' 'cf-select Dsgp915rwptemp .a2'
#ifndef UAV
	entry 'Temperature (a1)' 'cf-select Dsgp915rwptemp .a1'
	entry 'Temperature (a0)' 'cf-select Dsgp915rwptemp .a0'
	entry 'Temperature (b1)' 'cf-select Dsgp915rwptemp .b1'
	line
#endif
	entry 'Wind (a2)' 'cf-select Dsgp915rwpwind .a2'
#ifndef UAV
	entry 'Wind (a1)' 'cf-select Dsgp915rwpwind .a1'
	entry 'Wind (a0)' 'cf-select Dsgp915rwpwind .a0'
	entry 'Wind (b1)' 'cf-select Dsgp915rwpwind .b1'
#endif
endmenu
	

#ifndef UAV
define widget tower-menu intmenu 'tower platforms'
	title 'Tower Platforms'
	line
	entry "25m 1-minute (a0)" 'cf-select sgp1twr25m .a0 temp'
	entry "60m 1-minute (a0)" 'cf-select sgp1twr60m .a0 temp'
	entry "30-minute 10x (a1)" 'cf-select sgp30twr10x .a1 temp'
	entry "25m 30-minute (a1)" 'cf-select sgp30twr25m .a1 temp'
	entry "60m 30-minute (a1)" 'cf-select sgp30twr60m .a1 temp'
#ifndef SAMEX
	entry 'Tower daily (a0)' 'cf-select Dsgp1440twr21x .a0 tdry'
	entry 'Tower 1-minute (a0)' 'cf-select Dsgp1twr21x .a0 tdry'
	entry 'Tower 1-minute (a1)' 'cf-select Dsgp1twr21x .a1 tdry'
	entry 'Tower 30-minute (a0)' 'cf-select Dsgp30twr21x .a0 tdry'
	entry 'Tower 30-minute (a1)' 'cf-select Dsgp30twr21x .a1 tdry'
#endif
endmenu
#endif

#ifndef UAV
define widget bsrn-menu intmenu 'bsrn platforms'
	title 'BSRN Platforms'
	line
#ifdef SAMEX
	entry 'BSRN (a1)' 'cf-select sgpbsrn .a1 nip'
#else
	entry 'BSRN (a0)' 'cf-select sgpbsrn .a0 nip'
	entry 'BSRN (a1)' 'cf-select sgpbsrn .a1 nip'
	entry 'BSRN Calculations (c1)' 'cf-select sgpbsrncalc .c1 nip'
#endif
endmenu
#endif

define widget mfr-menu intmenu 'mfr platforms'
	title 'Multi-filtering Radiometer'
	line
#ifndef UAV
	entry 'MFR 10-meter (a1)' \
		'cf-select Dsgpmfr10m .a1 mfr_up_hemisp_broadband'
#endif
	entry 'MFR 25-meter (a1)' \
		'cf-select Dsgpmfr25m .a1 mfr_up_hemisp_broadband'
endmenu

define widget mwr-menu intmenu 'mwr platforms'
	title 'Microwave Radiometer'
	line
	entry 'MWRLOS (a1)' 'cf-select sgpmwrlos .a1 vap'
	entry 'MWRTIP (a0)' 'cf-select sgpmwrtip .a0 vap'
	entry '5 MWRAVG (c1)' 'cf-select sgp5mwravg .c1 vap'
endmenu

define widget blc-menu intmenu 'blc platforms'
	title 'Bellfort Laser Ceilometer'
	line
	entry 'BLC Level a1' 'cf-select sgpblc .a1 cloud1'
#ifdef notdef
!
! No a0 data
!
!	entry 'BLC Level a0' 'cf-select sgpblc .a0 cloud1'
#endif
endmenu

!
! Stuff called out of the above
!
procedure cf-select instrument string level string field string
	local context icon_platform
!
! For now just force the 'icon_platform' to C1
!
	set icon_platform 'C1'
	local platform concat3(instrument,icon_platform,level)
	local dmcmd quote(concat4('PutScalar ', platform, ' ', field))
	dm #dmcmd
endprocedure

procedure cf-sonde-select instrument string level string field string
	set icon_platform 'C1'
	local platform concat3(instrument,icon_platform,level)
	local dmcmd quote(concat4('PutSonde ', platform, ' ', field))
	dm "require PutSonde"
	dm #dmcmd
	set icon_platform context
endprocedure

