! $Id: cf-active-loc.cpp,v 1.3 1995-09-10 14:56:26 granger Exp $
!
! ------------------------------------------------------------------------
! DO NOT EDIT THIS FILE if it has been installed in the project directory
! tree. This file is generated from a cpp source file in the ./src directory!
! ------------------------------------------------------------------------
!
! Support for active facility locations.
!

!
! Include access to the E13 instruments, since our active area is
! covering E13's active area.
!
require 'ef-active-loc'

!
! Menu for platforms available at a central facility
!
define widget cf-send-menu intmenu 'cf instrument sender'
	title 'Central Facility Instruments'
	line
	submenu '50-MHz RASS' 'rass-50-menu'
	submenu '915-MHz RASS' 'rass-915-menu'
#ifndef UAV
	submenu 'Tower Platforms' 'tower-menu'
	submenu 'BSRN' 'bsrn-menu'
#endif
	submenu 'MFR' 'mfr-menu'
	entry 'SONDE (a1)' 'cf-select sgpsonde .a1 pres'
	entry 'MWRLOS (a1)' 'cf-select sgpmwrlos .a1 vap'
	line
	submenu 'E13 Instruments' ef-send-menu	
endmenu


define widget rass-50-menu intmenu 'rass platforms'
	title '50 MHz RASS Profiler'
	line
	entry 'Temperature (a2)' 'cf-select Dsgp50rwptemp .a2 temp'
#ifndef UAV
	entry 'Temperature (a1)' 'cf-select Dsgp50rwptemp .a1 temp'
	entry 'Temperature (a0)' 'cf-select Dsgp50rwptemp .a0 temp'
	entry 'Temperature (b1)' 'cf-select Dsgp50rwptemp .b1 temp'
	line
#endif
	entry 'Wind (a2)' 'cf-select Dsgp50rwpwind .a2 none'
#ifndef UAV
	entry 'Wind (a1)' 'cf-select Dsgp50rwpwind .a1 none'
	entry 'Wind (a0)' 'cf-select Dsgp50rwpwind .a0 none'
	entry 'Wind (b1)' 'cf-select Dsgp50rwpwind .b1 none'
#endif
endmenu
	

define widget rass-915-menu intmenu 'rass platforms'
	title '915 MHz RASS Profiler'
	line
	entry 'Temperature (a2)' 'cf-select Dsgp915rwptemp .a2'
#ifndef UAV
	entry 'Temperature (a1)' 'cf-select Dsgp915rwptemp .a1'
	entry 'Temperature (a0)' 'cf-select Dsgp915rwptemp .a0'
	entry 'Temperature (b1)' 'cf-select Dsgp915rwptemp .b1'
	line
#endif
	entry 'Wind (a2)' 'cf-select Dsgp915rwpwind .a2'
#ifndef UAV
	entry 'Wind (a1)' 'cf-select Dsgp915rwpwind .a1'
	entry 'Wind (a0)' 'cf-select Dsgp915rwpwind .a0'
	entry 'Wind (b1)' 'cf-select Dsgp915rwpwind .b1'
#endif
endmenu
	

#ifndef UAV
define widget tower-menu intmenu 'tower platforms'
	title 'Tower Platforms'
	line
	entry 'Tower daily (a0)' 'cf-select Dsgp1440twr21x .a0 tdry'
	entry 'Tower 1-minute (a0)' 'cf-select Dsgp1twr21x .a0 tdry'
	entry 'Tower 1-minute (a1)' 'cf-select Dsgp1twr21x .a1 tdry'
	entry 'Tower 30-minute (a0)' 'cf-select Dsgp30twr21x .a0 tdry'
	entry 'Tower 30-minute (a1)' 'cf-select Dsgp30twr21x .a1 tdry'
endmenu
#endif

#ifndef UAV
define widget bsrn-menu intmenu 'bsrn platforms'
	title 'BSRN Platforms'
	line
	entry 'BSRN (a0)' 'cf-select sgpbsrn .a0 nip'
	entry 'BSRN (a1)' 'cf-select sgpbsrn .a1 nip'
	entry 'BSRN Calculations (c1)' 'cf-select sgpbsrncalc .c1 nip'
endmenu
#endif

define widget mfr-menu intmenu 'mfr platforms'
	title 'Multi-filtering Radiometer'
	line
#ifndef UAV
	entry 'MFR 10-meter (a1)' \
		'cf-select Dsgpmfr10m .a1 mfr_up_hemisp_broadband'
#endif
	entry 'MFR 25-meter (a1)' \
		'cf-select Dsgpmfr25m .a1 mfr_up_hemisp_broadband'
endmenu


define widget blc-menu intmenu 'blc platforms'
	title 'Bellfort Laser Ceilometer'
	line
	entry 'BLC Level a1' 'cf-select sgpblc .a1 cloud1'
#ifdef notdef
!
! No a0 data
!
!	entry 'BLC Level a0' 'cf-select sgpblc .a0 cloud1'
#endif
endmenu

!
! Stuff called out of the above
!
procedure cf-select instrument string level string field string

!
! For now just force the 'icon_platform' to C1
!
	set icon_platform 'C1'
	local platform concat3(instrument,icon_platform,level)
	local dmcmd quote(concat4('PutScalar ', platform, ' ', field))
	dm #dmcmd
endprocedure


