! $Id: ds.config.cpp,v 1.13 1999-04-13 21:56:52 granger Exp $
!
! ------------------------------------------------------------------------
! DO NOT EDIT THIS FILE if it resides in the top level of the project
! configuration.  This file is generated from a cpp source file in the
! ./src directory!
! ------------------------------------------------------------------------
!
! Data store configuration file.
!
! Platform parameters:
!	organization 	The expected organization of the data
!		3dgrid		three dimensional regular grid
!		2dgrid		two-dimensional regular grid
!		irgrid		two-dimensional irregular grid (PAM)
!		scalar		basic scalar point data
!		nspace		multi-dimensional data
!		outline		Boundaries
!	filetype
!		netcdf, boundary, raster, compressed_raster, zeb,
!		grib, grib_sfc, grads
!
!	keep 		The minimum time period of data to keep on the disk if
!			at all possible.
!	maxsamples 	The maximum number of data samples to put into one
!		      	disk file.
!	mobile		Indicates that the data collection platform moves
!			through space.  For soundings, aircraft.
!	composite	This "platform" is a grouping of several smaller
!			platforms.  Only irgrid platforms -- groupings of
!			stationary scalar platforms -- are supported now.
!	directory	The directory in which to find data for this
!			platform.
!	model		Model data existing at both issue and forecast times
!

#include "config.h"

! Path to the production data directory.
!
if (getenv("DATAHOME") <> "UNDEFINED")
	set datadir getenv("DATAHOME")
else
	set datadir CFG_DATAHOME
endif
message "Production data directory: #" datadir

set dbfile concat3(CFG_PROJECTDIR,"/",CFG_DSCACHEFILE)
message "Using database file: #" dbfile

!
! A default source for all of the platforms
!
source default
	Directory #datadir
	CacheFile #dbfile
	DirConst true
	FileConst true
	DelayDataDirs true
endsource
	
! ================================================================ Real-time
#ifdef REALTIME

!
! Rescan all platforms then update the unified cache every 5 minutes.
!
procedure Update
	rescan all
	local update concat3("'",CacheFile,"'")
	local update concat("cache ",update)
	#update
endprocedure

set cmd "Update"
set cmd quote(cmd)
every 300 #cmd
message "Updating unified cache every 5 minutes." 

!
! Set to data store to rescan every 5 minutes
!
!every 300 'rescan all'
!message "Rescanning all platforms every 5 minutes"

#endif /* REALTIME */
! ================================================================ Real-time


!========================================================================
! Optional platforms
!========================================================================

set facility_nodes 	1
set sgp30ebbr_a0 	1
set sgp15ebbr_a0 	1
set sgp30ebbr_b2 	1
set smos1_a1 		1
set smos_daily 		1
set siros_b1 		1
set siros_c1 		1
set sonde_all_modes 	1
set sgp5mwravg      1
set sgpqmemwrcol    1
set sgpmwrtip 		1
set sgpmwrlosB_a0	1
set sgpmwslosB_b2 	1
set spgwvrlos		1

!========================================================================
! Facility nodes
!========================================================================

class Facility
	abstract
	virtual
	filetype	netcdf
	organization	scalar
endclass

class CentralFacility Facility
	virtual
endclass

class BoundaryFacility Facility
	virtual
endclass

class ExtendedFacility Facility
	virtual
endclass

if (facility_nodes)
!
! Facility instances serve as nodes in the hierarchy of
! sites and instruments.  Facility<->subplat connection represents
! co-location.
!
instance ExtendedFacility E1 E2 E3 E4 E5 E6 E7 E8 E9 E10 E11 E12 E13 E14
instance ExtendedFacility E15 E16 E17 E18 E19 E20 E21 E22 E23 E24 E25 E99

instance BoundaryFacility B1 B2 B3 B4 B5 B6

instance CentralFacility C1

endif

#ifndef UAV
!========================================================================
! EBBR -- E-Bowen Broadband Radiometer?  
!========================================================================

class EBBR
	organization	scalar
	filetype	netCDF
	maxsamples	10000
	daysplit
endclass EBBR

! E2
instance EBBR sgp5ebbrE2.a0 sgp15ebbrE2.a1 sgp30ebbrE2.a1

! E4
instance EBBR sgp5ebbrE4.a0 sgp15ebbrE4.a1 sgp30ebbrE4.a1

! E7 
instance EBBR sgp5ebbrE7.a0 sgp15ebbrE7.a1 sgp30ebbrE7.a1

! E8
instance EBBR sgp5ebbrE8.a0 sgp15ebbrE8.a1 sgp30ebbrE8.a1

! E9
instance EBBR sgp5ebbrE9.a0 sgp15ebbrE9.a1 sgp30ebbrE9.a1

! E12
instance EBBR sgp5ebbrE12.a0 sgp15ebbrE12.a1 sgp30ebbrE12.a1

! E13
instance EBBR sgp5ebbrE13.a0 sgp15ebbrE13.a1 sgp30ebbrE13.a1

! E15
instance EBBR sgp5ebbrE15.a0 sgp15ebbrE15.a1 sgp30ebbrE15.a1

! E18
instance EBBR sgp5ebbrE18.a0 sgp15ebbrE18.a1 sgp30ebbrE18.a1

! E20
instance EBBR sgp5ebbrE20.a0 sgp15ebbrE20.a1 sgp30ebbrE20.a1

! E22
instance EBBR sgp5ebbrE22.a0 sgp15ebbrE22.a1 sgp30ebbrE22.a1

! E24
instance EBBR sgp5ebbrE24.a0 sgp15ebbrE24.a1 sgp30ebbrE24.a1

! E26
instance EBBR sgp5ebbrE26.a0 sgp15ebbrE26.a1 sgp30ebbrE26.a1

!
! No 30-minute a0 data
!
if (sgp30ebbr_a0) 
	instance EBBR sgp30ebbrE2.a0
	instance EBBR sgp30ebbrE4.a0
	instance EBBR sgp30ebbrE7.a0
	instance EBBR sgp30ebbrE8.a0
	instance EBBR sgp30ebbrE9.a0
	instance EBBR sgp30ebbrE12.a0
	instance EBBR sgp30ebbrE13.a0
	instance EBBR sgp30ebbrE15.a0
	instance EBBR sgp30ebbrE18.a0
	instance EBBR sgp30ebbrE19.a0
	instance EBBR sgp30ebbrE20.a0
	instance EBBR sgp30ebbrE22.a0
	instance EBBR sgp30ebbrE25.a0
	instance EBBR sgp30ebbrE26.a0
endif

!
! No ebbr 15-minute a0 data
!
if (sgp15ebbr_a0)
    instance EBBR sgp15ebbrE2.a0 
    instance EBBR sgp15ebbrE4.a0 
	instance EBBR sgp15ebbrE7.a0 
	instance EBBR sgp15ebbrE8.a0
    instance EBBR sgp15ebbrE9.a0
    instance EBBR sgp15ebbrE12.a0 
	instance EBBR sgp15ebbrE13.a0 
    instance EBBR sgp15ebbrE15.a0
    instance EBBR sgp15ebbrE18.a0
    instance EBBR sgp15ebbrE19.a0
    instance EBBR sgp15ebbrE20.a0 
    instance EBBR sgp15ebbrE22.a0 
	instance EBBR sgp15ebbrE25.a0 
	instance EBBR sgp15ebbrE26.a0 
endif

#endif /* ! UAV */

!=====================================================================
! SMOS -- Surface Meteorology Observation System?
!=====================================================================

class SMOS
	organization	scalar
	filetype	netCDF
	maxsamples	10000
	daysplit
endclass

#ifdef UAV

instance SMOS sgp30smosE9.a1 sgp30smosE13.a1
instance SMOS sgp30smosE15.a1 sgp30smosE20.a1

#else

! E1
instance SMOS sgp1smosE1.a0 
instance SMOS sgp30smosE1.a1

! E3
instance SMOS sgp1smosE3.a0
instance SMOS sgp30smosE3.a1

! E4
instance SMOS sgp1smosE4.a0
instance SMOS sgp30smosE4.a1

! E5
instance SMOS sgp1smosE5.a0
instance SMOS sgp30smosE5.a1

! E6
instance SMOS sgp1smosE6.a0
instance SMOS sgp30smosE6.a1

! E7
instance SMOS sgp1smosE7.a0
instance SMOS sgp30smosE7.a1

! E8
instance SMOS sgp1smosE8.a0
instance SMOS sgp30smosE8.a1

! E9
instance SMOS sgp1smosE9.a0
instance SMOS sgp30smosE9.a1

! E11
instance SMOS sgp1smosE11.a0
instance SMOS sgp30smosE11.a1

! E13
instance SMOS sgp1smosE13.a0
instance SMOS sgp30smosE13.a1

! E15
instance SMOS sgp1smosE15.a0
instance SMOS sgp30smosE15.a1

! E20
instance SMOS sgp1smosE20.a0
instance SMOS sgp30smosE20.a1

! E22
!instance SMOS sgp1smosE21.a0
!instance SMOS sgp30smosE22.a1

! E24
instance SMOS sgp1smosE24.a0
instance SMOS sgp30smosE24.a1

! E25
instance SMOS sgp1smosE25.a0
instance SMOS sgp30smosE25.a1

!! E99
!instance SMOS sgp1smosE99.a0
!instance SMOS sgp30smosE99.a1

if (smos1_a1)
! E1
instance SMOS sgp1smosE1.a1

! E3
instance SMOS sgp1smosE3.a1

! E4
instance SMOS sgp1smosE4.a1

! E5
instance SMOS sgp1smosE5.a1

! E6
instance SMOS sgp1smosE6.a1

! E7
instance SMOS sgp1smosE7.a1

! E8
instance SMOS sgp1smosE8.a1

! E9
instance SMOS sgp1smosE9.a1

! E11
instance SMOS sgp1smosE11.a1

! E13
instance SMOS sgp1smosE13.a1

! E15
instance SMOS sgp1smosE15.a1

! E20
instance SMOS sgp1smosE20.a1

! E21
!instance SMOS sgp1smosE21.a1

! E24
instance SMOS sgp1smosE24.a1

! E25
instance SMOS sgp1smosE25.a1

!! E99
!instance SMOS sgp1smosE99.a1
endif

class SMOS-Daily SMOS
	maxsamples	1
endclass

!
! 
!
!	instance SMOS-Daily Dsgp1440smosE99.a0
if (smos_daily)
	instance SMOS-Daily sgp1440smosE1.a0
	instance SMOS-Daily sgp1440smosE3.a0
	instance SMOS-Daily sgp1440smosE4.a0
	instance SMOS-Daily sgp1440smosE5.a0
	instance SMOS-Daily sgp1440smosE6.a0
	instance SMOS-Daily sgp1440smosE7.a0
	instance SMOS-Daily sgp1440smosE8.a0
	instance SMOS-Daily sgp1440smosE9.a0
	instance SMOS-Daily sgp1440smosE11.a0
	instance SMOS-Daily sgp1440smosE13.a0
	instance SMOS-Daily sgp1440smosE15.a0
	instance SMOS-Daily sgp1440smosE20.a0
	instance SMOS-Daily sgp1440smosE21.a0
	instance SMOS-Daily sgp1440smosE24.a0
	instance SMOS-Daily sgp1440smosE25.a0
endif
#endif /* ! UAV */

!======================================================================
! Eddy Correlation
!======================================================================

class ecorpr
	organization	scalar
	filetype	netCDF
endclass

instance ecorpr sgp30ecorprE14.a1

!=====================================================================
! Best Estimate Shortwave Irradiances 
!=====================================================================

class swrad
	organization	scalar
	filetype	netCDF
endclass

instance swrad sgpswradC1.c1

!=====================================================================
! SIROS 
!=====================================================================

class SIROS
	organization	scalar
	filetype	netCDF
	maxsamples	10000
	daysplit
endclass

class SIROS-Depth SIROS
	maxsamples	2
endclass

#ifdef UAV

instance SIROS DsgpsirosE8.a1
instance SIROS DsgpsirosE11.a1 DsgpsirosE13.a1
instance SIROS DsgpsirosE15.a1 DsgpsirosE16.a1

#else
/*
instance SIROS DsgpsirosE1.a1 
instance SIROS DsgpsirosE2.a1 
instance SIROS DsgpsirosE3.a1
instance SIROS DsgpsirosE4.a1 
instance SIROS DsgpsirosE5.a1 
instance SIROS DsgpsirosE6.a1
instance SIROS DsgpsirosE7.a1 
instance SIROS DsgpsirosE8.a1 
instance SIROS DsgpsirosE9.a1
instance SIROS DsgpsirosE10.a1 
instance SIROS DsgpsirosE11.a1 
instance SIROS DsgpsirosE13.a1
instance SIROS DsgpsirosE15.a1
instance SIROS DsgpsirosE16.a1
instance SIROS DsgpsirosE18.a1
instance SIROS DsgpsirosE20.a1
instance SIROS DsgpsirosE22.a1
instance SIROS DsgpsirosE24.a1
*/
instance SIROS sgpsirosE1.a1 
instance SIROS sgpsirosE2.a1 
instance SIROS sgpsirosE3.a1
instance SIROS sgpsirosE4.a1 
instance SIROS sgpsirosE5.a1 
instance SIROS sgpsirosE6.a1
instance SIROS sgpsirosE7.a1 
instance SIROS sgpsirosE8.a1 
instance SIROS sgpsirosE9.a1
instance SIROS sgpsirosE10.a1 
instance SIROS sgpsirosE11.a1 
instance SIROS sgpsirosE13.a1
instance SIROS sgpsirosE15.a1
instance SIROS sgpsirosE16.a1
instance SIROS sgpsirosE18.a1
instance SIROS sgpsirosE20.a1
instance SIROS sgpsirosE22.a1
instance SIROS sgpsirosE24.a1

!
! No b1 data yet
!
if (siros_b1)
	instance SIROS DsgpsirosE4.b1 DsgpsirosE7.b1 DsgpsirosE9.b1
	instance SIROS DsgpsirosE13.b1 DsgpsirosE15.b1 DsgpsirosE20.b1 
	instance SIROS DsgpsirosE22.b1
endif

!
! No c1 data yet
!
if (siros_c1)
    instance SIROS-Depth DsgpsirosopdepthE4.c1 DsgpsirosopdepthE7.c1
    instance SIROS-Depth DsgpsirosopdepthE9.c1 DsgpsirosopdepthE13.c1
    instance SIROS-Depth DsgpsirosopdepthE15.c1 DsgpsirosopdepthE20.c1
    instance SIROS-Depth DsgpsirosopdepthE22.c1
endif

#endif /* ! UAV */


#ifndef UAV
!===================================================================
! BSRN
!===================================================================

class BSRN
	organization	scalar
	filetype	netCDF
	maxsamples	10000
	daysplit
endclass

class BSRN-Calc BSRN
	organization	scalar
	filetype	netCDF
	maxsamples	2000
	daysplit
endclass

instance BSRN sgpbsrnC1.a1 sgpbsrnC1.a0
instance BSRN-Calc sgpbsrncalcC1.c1

#endif /* ! UAV */

!======================================================================
! BLC -- Bellfort Laser Ceilometer
!======================================================================

class BLC
	organization	scalar
	filetype	netCDF
	maxsamples	10000
	daysplit
endclass

#ifndef UAV
instance BLC sgpblcC1.a0
#endif
instance BLC sgpblcC1.a1

#ifndef UAV
!=====================================================================
! LBL
!=====================================================================

class LBL
	organization	scalar
	filetype	netCDF
	maxsamples	10000
endclass

instance LBL sgplblch1C1.c1
instance LBL sgplblch1aC1.c1 sgplblch1bC1.c1 sgplblch2C1.c1
#endif

#ifndef UAV
!=====================================================================
! MFRSR -- Multi-filter Rotating Shadowband Radiometer
!=====================================================================

class MFRSR
	organization	irgrid
	filetype	netCDF
	maxsamples	10000	
	regular		15
	daysplit
	composite
endclass

class MFRSR-Subplat MFRSR
	organization	scalar
endclass

subplats MFRSR MFRSR-Subplat 1

instance MFRSR sgpmfrsrN1.a0

#endif /* ! UAV */

!====================================================================
! Sondes - some Sonde platforms are under development data
!====================================================================

class Sonde
	organization	scalar
	filetype	netCDF
	maxsamples	4000
	mobile
endclass

!----- C1
instance Sonde sgpsondewrpnC1.a1 

!----- B1
instance Sonde sgpsondewrpnB1.a1 


!----- B4
instance Sonde sgpsondewrpnB4.a1

!----- B5
instance Sonde sgpsondewrpnB5.a1 

!----- B6
instance Sonde sgpsondewrpnB6.a1


!========================================================================
! Profiler
!========================================================================

class Profiler
	organization	nspace
	filetype	netCDF
	maxsamples	10000
	daysplit
endclass Profiler

class Profiler915 Profiler
endclass

class Profiler50 Profiler
endclass

class Profiler915-Wind-A0 Profiler915
	maxsamples	1008
endclass

instance Profiler915 sgp915rwptempC1.a0 sgp915rwptempC1.a1
instance Profiler915 sgp915rwptempC1.b1 sgp915rwptempC1.a2

instance Profiler915 sgp915rwpwindC1.a1 sgp915rwpwindC1.b1 
instance Profiler915 sgp915rwpwindC1.a2
instance Profiler915-Wind-A0 sgp915rwpwindC1.a0

class Profiler50-Wind-A0 Profiler50
	maxsamples	504
endclass

instance Profiler50 sgp50rwptempC1.b1 sgp50rwptempC1.a2 sgp50rwptempC1.a1
instance Profiler50 sgp50rwptempC1.a0

instance Profiler50 sgp50rwpwindC1.b1 sgp50rwpwindC1.a2 sgp50rwpwindC1.a1
instance Profiler50-Wind-A0 sgp50rwpwindC1.a0


!=======================================================================
! MWR -- Microwave Radiometer  - some MWR platforms are under development data
!=======================================================================

class MWR
	organization	scalar
	filetype	netCDF
	maxsamples	10000
	daysplit
endclass

class MWR-LOS MWR
endclass

class MWR-Average MWR
	regular		300
	maxsamples	288
endclass

class MWR-TIP MWR
endclass

class MWR-Column MWR
endclass

class MWR-Profile MWR
	maxsamples	2140
endclass

! C1
instance MWR-LOS sgpmwrlosC1.a0 sgpmwrlosC1.a1
instance MWR-Average sgp1mwravgC1.c1
!instance MWR-Profile sgpmwrprofC1.c1

! B1
instance MWR-LOS sgpmwrlosB1.a0 sgpmwrlosB1.a1

! B4
instance MWR-LOS sgpmwrlosB4.a0 sgpmwrlosB4.a1

! B5
instance MWR-LOS sgpmwrlosB5.a0 sgpmwrlosB5.a1

! B6
instance MWR-LOS sgpmwrlosB6.a0 sgpmwrlosB6.a1

if (sgpqmemwrcol)
    instance MWR-Column sgpqmemwrcolC1.c1
    instance MWR-Column sgpqmemwrcolB1.c1
    instance MWR-Column sgpqmemwrcolB4.c1
    instance MWR-Column sgpqmemwrcolB5.c1
    instance MWR-Column sgpqmemwrcolB6.c1
endif

if (sgp5mwravg)
	instance MWR-LOS sgp5mwravgC1.c1
	instance MWR-LOS sgp5mwravgB1.c1
	instance MWR-LOS sgp5mwravgB4.c1
	instance MWR-LOS sgp5mwravgB5.c1
	instance MWR-LOS sgp5mwravgB6.c1
endif

if (sgpmwrtip)
	instance MWR-TIP sgpmwrtipC1.a0 sgpmwrtipC1.a1
	instance MWR-TIP sgpmwrtipB1.a0 sgpmwrtipB1.a1
	instance MWR-TIP sgpmwrtipB4.a0 sgpmwrtipB4.a1
	instance MWR-TIP sgpmwrtipB5.a0 sgpmwrtipB5.a1
	instance MWR-TIP sgpmwrtipB6.a0 sgpmwrtipB6.a1
endif


!======================================================================
! AERI
!======================================================================

class AERI
        organization	scalar
        filetype	netCDF
        maxsamples	10000
        daysplit
endclass

instance AERI sgpaerich1C1.a1 sgpaerich2C1.a1 sgpaerisummaryC1.a1
instance AERI sgpqmeaerilblC1.c1 sgpqmeaerimeansC1.c1 sgpaerilbldiffC1.c1
instance AERI sgpaerilblcloudsC1.c1



!======================================================================
! WVR
!======================================================================

class WVR
	organization	scalar
	filetype	netCDF
	maxsamples	5000
	composite
	daysplit
endclass

if (spgwvrlos)
	instance WVR sgpwvrlosC1.a1
endif


!======================================================================
! WSI Cloud
!======================================================================

class WSI
	organization	scalar
	filetype	netCDF
	maxsamples	10000
	daysplit
endclass

instance WSI sgpwsicloudC1.c1


!========================================================================
! Development Data
!========================================================================
!
! Use the value of DEVDATAHOME for the development data directory, if
! available, else leave datadir as it was set for production data above.
!
if (getenv("DEVDATAHOME") <> "UNDEFINED")
        set datadir getenv("DEVDATAHOME")
else
	set datadir CFG_DEVDATAHOME
endif
message "Development data directory: #" datadir

!========================================================================
! EBBR -- E-Bowen Broadband Radiometer?  Continued from production data
!========================================================================
!
! No data for 30-minute ebbr b2 level yet
!
if (sgp30ebbr_b2)
	instance EBBR Dsgp30ebbrE15.b2 Dsgp30ebbrE13.b2 Dsgp30ebbrE12.b2
	instance EBBR Dsgp30ebbrE9.b2 Dsgp30ebbrE8.b2 Dsgp30ebbrE7.b2
	instance EBBR Dsgp30ebbrE4.b2 Dsgp30ebbrE26.b2 Dsgp30ebbrE22.b2
	instance EBBR Dsgp30ebbrE20.b2
endif


!===================================================================
! Tower platforms
!===================================================================

class Tower
	organization	scalar
	filetype	netCDF
	maxsamples	10000
	daysplit
endclass

instance Tower sgp1twr25mC1.a0 sgp1twr60mC1.a0
instance Tower sgp30twr25mC1.a1 sgp30twr60mC1.a1
instance Tower sgp30twr10xC1.a1
instance Tower sgp1twr21xC1.a1 sgp1twr21xC1.a0 sgp30twr21xC1.a1
instance Tower sgp30twr21xC1.a0 sgp1440twr21xC1.a0

!====================================================================
! MFR -- Multi-filter Radiometer
!====================================================================

class MFR
	organization	scalar
	filetype	netCDF
	maxsamples	10000
	daysplit
endclass

instance MFR Dsgpmfr10mC1.a1
instance MFR Dsgpmfr25mC1.a1


!=====================================================================
! MPL -- Micropulse LIDAR
!=====================================================================

class MPL
	organization	scalar
	filetype	netCDF
	maxsamples	10000
	daysplit
endclass

instance MPL DsgpmplC1.a0
instance MPL DsgpmplcbhC1.c1


!====================================================================
! Sondes (continued from production data)
!====================================================================

!----- C1
!instance Sonde DsgpsondewndcalcC1.c1

if (sonde_all_modes)
instance Sonde sgpsondewnpnC1.a0 sgpsondewnpnC1.a1 sgpsondewnprC1.a0
instance Sonde sgpsondewnprC1.a1 sgpsondewrprC1.a0 sgpsondewrprC1.a1
instance Sonde sgpsondewrpnC1.a0
endif

!----- B1
!instance Sonde DsgpsondewndcalcB1.c1

if (sonde_all_modes)
instance Sonde DsgpsondewnpnB1.a0 DsgpsondewnpnB1.a1 DsgpsondewnprB1.a0
instance Sonde DsgpsondewnprB1.a1 DsgpsondewrprB1.a0 DsgpsondewrprB1.a1
instance Sonde DsgpsondewrpnB1.a0 
endif

!----- B4
!instance Sonde DsgpsondewndcalcB4.c1

if (sonde_all_modes)
instance Sonde DsgpsondewnpnB4.a0 DsgpsondewnpnB4.a1 DsgpsondewnprB4.a0
instance Sonde DsgpsondewnprB4.a1 DsgpsondewrprB4.a0 DsgpsondewrprB4.a1
instance Sonde DsgpsondewrpnB4.a0 
endif

!----- B5
!instance Sonde DsgpsondewndcalcB5.c1

if (sonde_all_modes)
instance Sonde DsgpsondewnpnB5.a0 DsgpsondewnpnB5.a1 DsgpsondewnprB5.a0
instance Sonde DsgpsondewnprB5.a1 DsgpsondewrprB5.a0 DsgpsondewrprB5.a1
instance Sonde DsgpsondewrpnB5.a0 
endif

!----- B6
!instance Sonde DsgpsondewndcalcB6.c1

if (sonde_all_modes)
instance Sonde DsgpsondewnpnB6.a0 DsgpsondewnpnB6.a1 DsgpsondewnprB6.a0
instance Sonde DsgpsondewnprB6.a1 DsgpsondewrprB6.a0 DsgpsondewrprB6.a1
instance Sonde DsgpsondewrpnB6.a0 
endif


!=======================================================================
! MWR -- Microwave Radiometer (continued from production data)
!=======================================================================

! not available as of 02/05/97
if (sgpmwrlosB_b2)
	instance MWR-LOS DsgpmwrlosB1.b2
	instance MWR-LOS DsgpmwrlosB4.b2
	instance MWR-LOS DsgpmwrlosB5.b2
	instance MWR-LOS DsgpmwrlosB6.b2
endif


!=======================================================================
! Platform NULLplatform is a nonexistant platform that nevertheless must
! exist in order for some BW-using modules' _retriever.info and/or
! _maker.info files to work. Nothing should actually ever be written here
! and the directory doesn't need to exist.  As long as DelayDataDirs
! is true, the directory will never be created.

platform NULLplatform
	organization	scalar
	filetype	netCDF
	maxsamples	1000
	daysplit
endplatform

!
! The null placeholder platform.
!
platform null
	organization	scalar
	filetype	zeb
endplatform


