! $Id: ef-active-loc.cpp,v 1.5 1999-04-13 21:56:53 granger Exp $
!
! ------------------------------------------------------------------------
! DO NOT EDIT THIS FILE if it has been installed in the project directory
! tree. This file is generated from a cpp source file in the ./src directory!
! ------------------------------------------------------------------------
!
! Support for active facility locations.
!

!
! Menu for platforms available at an extended facility
!
define widget ef-send-menu intmenu 'ef instrument sender'
	title 'Extended Facility Instruments'
	line
	submenu 'SMOS Platforms' 'ef-smos-menu'
#ifndef UAV
	submenu 'EBBR Platforms' 'ef-ebbr-menu'
#endif
	entry 'SIROS (a1)' 'ef-select sgpsiros .a1 hemisp_broadband'
	entry 'Eddy Corr 30m (E14, a1)' 'ef-select sgp30ecorpr .a1 mean_q'
endmenu

define widget ef-smos-menu intmenu 'ef smos platforms'
	title 'SMOS Platforms'
	line
#ifdef SAMEX
	entry '1-minute (a0)' 'ef-select sgp1smos .a0 temp'
	entry '30-minute (a1)' 'ef-select sgp30smos .a1 temp'
	entry 'daily (a0)' 'ef-select sgp1440smos .a0 temp'
#else
#ifndef UAV
	entry '1-minute (a0)' 'ef-select sgp1smos .a0 temp'
	entry '1-minute (a1)' 'ef-select sgp1smos .a1 temp'
	entry '30-minute (a0)' 'ef-select sgp30smos .a0 temp'
#endif
	entry '30-minute (a1)' 'ef-select sgp30smos .a1 temp'
	entry 'daily (a0)' 'ef-select sgp1440smos .a0 temp'
#endif
endmenu

#ifndef UAV
define widget ef-ebbr-menu intmenu 'ef ebbr platforms'
	title 'EBBR Platforms'
	line
#ifdef SAMEX
	entry '30-minute (a1)' 'ef-select sgp30ebbr .a1 temp'
#else
	entry '5-minute (a0)' 'ef-select sgp5ebbr .a0 temp'
	entry '15-minute (a1)' 'ef-select sgp15ebbr .a1 temp'
	entry '30-minute (a1)' 'ef-select sgp30ebbr .a1 temp'
#endif
endmenu
#endif

!
! Stuff called out of the above
!
procedure ef-select instrument string level string field string
	local context icon_platform
!
! It's possible we're called from the Central Facility or
! the iconbar, in which case we are actually platform E13.
!
	if (instrument = 'sgp30ecorpr')
		set icon_platform 'E14'
	elseif (icon_platform = "iconbar")
		set icon_platform 'E13'
	elseif (icon_platform = 'CF')
		set icon_platform 'E13'
	elseif (icon_platform = 'C1')
		set icon_platform 'E13'
	endif
	local platform concat3(instrument,icon_platform,level)
	local dmcmd quote(concat4('PutScalar ', platform, ' ', field))
	dm #dmcmd
	set icon_platform context
endprocedure

