! $Id: IconBar.cpp,v 1.10 1995-09-22 00:14:02 granger Exp $
! 
! ------------------------------------------------------------------------
! DO NOT EDIT THIS FILE if it resides in the top level of the project
! configuration.  This file is generated from a cpp source file in the
! ./src directory!
! ------------------------------------------------------------------------
!
! All the definitions required to make the iconbar work.
!

! I put the iconbar icons in the project icon directory, copying those needed
! from the library icon directory.  This avoids copying project icons into
! the library directory or hard-coding the library directory path in the
! iconbar; both those options are unsatisfactory.
!
set ui$bitmap_directory concat(c$projdir,"/icons")

!
! Display manager modules which this IconBar requires
!
require "init-config-menu"
require "cfg-tools"
require "send-wbounds"
require "put_component"
require "vor-popup"
require "ISS-Send-Locs"
require "ModelAdd"
!require "template-menu"

!
! This is the iconbar menu itself.....
!
define widget iconbar menubar " "
	!
	! All this stuff tells the system to put it, unadorned by headers and
	! title bars, where we want it.  DM does "override" by itself now,
	! since this iconbar appears in the display config, so we don't
	! bother with it here.
	!
	noheader
	! size 230 80
	location 100 100
	! vertical
	! override
	!
	! Now we can define the menus themselves.
	!
	menu help bitmap iconbar-help
		title 'Zebra Help Access'
		line
		entry 'Introduction' 'help intro'
		entry 'On-line Help Index' 'help index'
		entry 'Starting Zebra' 'help start'
		entry 'Shutting Down' 'help shut-down'
		entry 'Keys and Mouse Buttons' 'help keys'
		entry 'The Icon Bar' 'help iconbar'
		entry 'Editing Display Configurations' 'help editing-configs'
		line
		entry 'Horizontal plots' 'help horizontal-plots'
		entry 'Skew-t plots' 'help skewt'
		entry 'XYGraph plots' 'help xy-graphs'
		entry 'Cross section plots' 'help cross-section'
		line
		entry 'ARM Help Index' 'help arm-index'
		entry 'ARM Display Index' 'help arm-displays'
		entry 'ARM Icon Bar' 'help arm-iconbar'
		line
		entry 'ARM Home Page' 'help "http://info.arm.gov/"'
		entry 'ARM Datasets Info' \
			'help "http://info.arm.gov/docs/data.html"'
		entry 'ARM Acronyms and Abbreviations' \
		   'help "http://info.arm.gov/docs/documents/acronyms.html"'
		entry 'ARM Archive at ORNL' \
			'help "http://www-armarchive.ornl.gov/"'
	endmenu
	menu tools bitmap tools-big
		title 'Tools'
		line
		entry 'Time Control Tool...' 'popup time'
		entry 'Printing Tool...' 'popup hardcopy'
		entry 'Configuration Tool...' 'popup ConfigEdit'
		entry 'XTerm Shell Tool' 'shell \
  "xterm -T ZebraShell -bg grey90 -fg purple -fn 8x13bold -e zstart -shell &"'
		submenu 'Data Listings' dslistings
		entry 'Data Store Management' 'shell "dsmanage &"'
		line
		entry 'Begin new configuration...' 'popup newconfig'
		submenu 'Add new window' 'template-menu'
		entry 'Kill window by cursor' 'point-and-shoot'
		entry 'Add window named...' 'popup NewWindow'
		entry 'Kill window named...' 'popup ZorchWindow'
		line
		entry 'Save this configuration' 'cfgsave #dm$config'
		entry 'Save this configuration as...' 'popup SaveConfig'
#ifdef notdef
		entry 'Remove this configuration' 'cfg-remove'
#endif
		entry 'Restore to original' 'cfg-restore'
		line
		entry 'Shutdown Zebra' 'shutdown'
	endmenu
	menu configs bitmap configs
		title 'Display configurations'
		line
		entry 'Empty screen' 'display empty' (dm$config = 'empty')
#ifndef UAV
		entry 'MM5 model' 'display mm5' (dm$config = 'mm5')
		entry 'MM5 cross sections' 'display mm5-xs' \
		      (dm$config = 'mm5-xs')
		entry 'Time-height and soundings' 'display iss-timeht' \
			(dm$config = 'iss-timeht')
		entry 'Sounding cross sections' 'display snd_xsect' \
		        (dm$config = 'snd_xsect')
		entry 'AERI LBL Clouds' 'display aericlouds' \
			(dm$config = 'aericlouds')
		entry 'RUC model' 'display ruc' (dm$config = 'ruc')
		entry 'Oklahoma Mesonet' 'display ok-mesonet' \
			(dm$config = 'ok-mesonet')
		entry 'Wind Profiler Demo Network' 'display wpdn' \
			(dm$config = 'wpdn')
#endif
		entry 'AVHRR/GOES Satellite' 'display satellite' \
			(dm$config = 'satellite')
		entry 'SMOS Time Series' 'display smos-tseries' \
			(dm$config = 'smos-tseries')
		entry 'Sonde Skew-t plots' 'display sondes' \
			(dm$config = 'sondes')
		entry 'UDF Track' 'display uav-track' (dm$config = 'uav-track')
		entry 'NWS Surface Mesonet' \
			'display Mesonet' (dm$config = 'Mesonet')
		entry '915 MHz Profiles' \
			'display Profiler915' (dm$config = 'Profiler915')
		entry '50 MHz Profiles' \
			'display Profiler50' (dm$config = 'Profiler50')
		entry 'BLC and MFR Time Series' \
			'display tseries' (dm$config = 'tseries')
#ifdef notdef
		submenu 'UAV Configurations' uav-config-menu
#endif
#ifdef notdef
!		entry 'ISS Line Plot' 'display iss-lineplot' \
!			(dm$config = 'iss-lineplot')
!		entry 'ISS LinePlot and TimeHeight' \
!			'display iss-lineplot-timeheight' \
!			(dm$config = 'iss-lineplot-timeheight')
!		entry 'ISS TimeHeight, SkewT, Temp' \
!			'display iss-timeheight-skew-temp' \
!			(dm$config = 'iss-timeheight-skew-temp')
#endif
		line
		submenu 'Saved Configurations' saved-config-menu
	endmenu
	menu surface bitmap surface
		title 'Surface Observations'
		line
		submenu 'NWS Mesonet' nwssurf
#ifndef UAV
		submenu 'Tower Platforms' tower-menu
		submenu 'Kansas Hourly' kansas-hourly
		submenu 'Kansas Daily' kansas-daily
		submenu 'Oklahoma 5-minute (a0)' oklahoma05a0
		submenu 'Oklahoma 5-minute (a1)' oklahoma05a1
		submenu 'Oklahoma 15-minute (a0)' oklahoma15a0
		submenu 'Oklahoma 15-minute (a1)' oklahoma15a1
		line
		submenu 'Wind Profiler Demo Network' 'wpdn-menu'
		submenu 'EBBR Instruments' 'ebbr-irgrid-menu'
#endif
		submenu 'SMOS Instruments' 'smos-irgrid-menu'
#ifdef notdef
!		line
!		entry 'ISS Surface data' 'ISS-Send-Stations'
!		line
!		entry 'Arkansas River Basin Precip' 'beep'
#endif
	endmenu
	menu radiometric bitmap radiation
		title 'Radiation'
		line
#ifdef UAV
		entry 'MFR 25m Central Facility (a1)' \
		   'PutScalar Dsgpmfr25mC1.a1 mfr_up_hemisp_broadband'
		entry 'CF Bellfort Laser Ceilometer (a1)' \
		   'PutScalar sgpblcC1.a1 cloud1'
		line
		submenu 'SIROS' siros
		submenu 'MWR Central Facility' mwr-cf-menu
#else
		submenu 'AERI Central Facility' aeri-menu
		line
		submenu 'MWR Central Facility' mwr-cf-menu
		submenu 'MWR Boundary Facility One' mwr-b1-menu
		submenu 'MWR Boundary Facility Four' mwr-b4-menu
		submenu 'MWR Boundary Facility Five' mwr-b5-menu
		line
		submenu 'MFRSR' mfrsr-menu
		line
		submenu 'SIROS' siros
		line
		entry 'MFR 10m Central Facility (a1)' \
		   'PutScalar Dsgpmfr10mC1.a1 mfr_up_hemisp_broadband'
		entry 'MFR 25m Central Facility (a1)' \
		   'PutScalar Dsgpmfr25mC1.a1 mfr_up_hemisp_broadband'
		line
		entry 'BSRN Central Facility (a1)' \
		   'PutScalar sgpbsrnC1.a1 nip'
		entry 'CF Whole Sky Imager' \
		   'PutScalar sgpwsicloudC1.c1 mean_cloud_height'
		entry 'CF Bellfort Laser Ceilometer (a1)' \
		   'PutScalar sgpblcC1.a1 cloud1'
#endif
	endmenu
#ifndef UAV
	menu model bitmap model
		title 'Model Grids'
		line
		entry 'RUC Contours' 'ModelAdd sgprucsX1.a1 pt yellow'
		entry 'RUC Wind Vectors' \
		   'ModelWindsAdd sgprucsX1.a1 yellow 50'
		entry 'RUC Analysis Contours' \
		   'ModelAdd sgprucsanalX1.a1 pt yellow'
		entry 'RUC Analysis Winds' \
		   'ModelWindsAdd sgprucsanalX1.a1 yellow 50'
		line
		entry 'MM5 Contours' 'ModelAdd mm5ncar pres green'
		entry 'MM5 Wind Vectors' 'ModelWindsAdd mm5ncar green 50'
		entry 'MM5 Surface Contours' \
		   'SfcModelAdd mm5ncar_sfc soil_temp brown'
		entry 'MM5 Surface Winds' \
		   'SfcModelWindsAdd mm5ncar_sfc brown 50'
		line
		entry 'NGM Contours' 'sendout p_ngm pick'
		entry 'NGM Wind Vectors' 'sendout p_ngm_winds pick'
	endmenu
#endif
	menu satellite bitmap satellite
		title 'Satellite Images'
		line
		entry 'GOES-8 5-channel (4 km)' \
		   'putc2 p_raster platform sgpgoes8X1.a1 field gvar_ch1'
		entry 'GOES-8 1-channel vis (1 km)' \
		   'putc2 p_raster platform sgpgoes8visX1.a1 field gvar_ch1'
		line
		entry 'AVHRR-12 Albedo and Brightness' \
		   'putc2 p_raster platform sgpavhrr12X1.a1 field avhrr_ch1'
		entry 'AVHRR-12 Radiances' \
		   'putc2 p_raster platform sgpavhrr12radX1.a1 field avhrr_ch3'
		entry 'AVHRR-14 Albedo and Brightness' \
		   'putc2 p_raster platform sgpavhrr14X1.a1 field avhrr_ch1'
		entry 'AVHRR-14 Radiances' \
		   'putc2 p_raster platform sgpavhrr14radX1.a1 field avhrr_ch3'
#ifndef UAV
		line
		entry 'GOES-Minnis' 'sendout c_goes_minnis pick'
#endif
#ifdef notdef
		entry 'AVHRR State Lines' \
   'putc2 p_satoverlay platform avhrr_sgp.state_lines field state_line'
		entry 'AVHRR Lat-Lon Grid' \
   'putc2 p_satoverlay platform avhrr_sgp.lat_lon field lat_lon_grid'
		line
		submenu 'GOES-7 Platforms' goes-7-menu
#endif
	endmenu
	menu sone bitmap sonde
		title 'Sonde Instruments'
		line
		entry 'C1 Sonde (wrpn)' \
			'require PutSonde; PutSonde sgpsondewrpnC1.a1 tdry'
		entry 'B1 Sonde (wrpn)' \
			'require PutSonde; PutSonde sgpsondewrpnB1.a1 tdry'
		entry 'B4 Sonde (wrpn)' \
			'require PutSonde; PutSonde sgpsondewrpnB4.a1 tdry'
		entry 'B5 Sonde (wrpn)' \
			'require PutSonde; PutSonde sgpsondewrpnB5.a1 tdry'
		entry 'B6 Sonde (wrpn)' \
			'require PutSonde; PutSonde sgpsondewrpnB6.a1 tdry'
	endmenu
	menu uav bitmap aircraft
		title 'UAV Platforms'
		line
		entry 'UAV Instrument Track' 'PutScalar uav met_temp'
		entry 'UAV Telemetry Track' \
		   'PutScalar sgpuavtrack alt'
#ifdef notdef
		entry 'UAV TDDR Time Series' \
		   'PutScalar DsgpuavtddrUg1.a1 tddr_opd'
		line
		entry 'GOES vis (UAV project)' \
		   'putc2 p_goes_uav platform sgpgoesvis.tmp field vis'
		entry 'GOES ir (UAV project)' \
		   'putc2 p_goes_uav platform sgpgoesir.tmp field ir'
		line
		submenu 'NGM plots from UAV' ngm-uav-menu
#endif
	endmenu
#ifdef notdef
	menu 'qme-vap' bitmap qme_vap
		title 'Quality Measurement Experiments'
		line
		submenu 'MWR Columns' qmemwrcol-menu
		submenu 'Sonde Wind Calculations' sondewndcalc-menu
		line
		entry 'Value Added Products' 'beep'
	endmenu
#endif
	menu 'overlays' bitmap overlays
		title 'Static Overlays'
		line
		entry 'State Lines' \
			'putc3 p_map platform state_lines color tan icon map'
		entry 'Cities' 'put_component c_city_labels'
		entry 'Roads' 'put_component c_ok-rd'
		entry 'Road Labels' 'put_component c_road_labels'
		entry 'Rivers' 'put_component c_ok-dn'
		entry 'Railroads' 'put_component c_ok-rr'
		entry 'Elevations' 'put_component c_ok-hy'
		line
		entry 'Central Facility' 'sendout p_cf_locns pick'
		entry 'Extended Facilities' 'sendout p_ef_locns pick'
		entry 'Boundary Facilities' 'sendout p_bf_locns pick'
		entry 'All Facilities' 'sendout p_all_locns pick'
		line
#ifndef UAV
		entry 'ISS Sounding locations' 'ISS-Send-Locs sounding'
		entry 'ISS Profiler locations' 'ISS-Send-Locs profiler'
		entry 'ISS RASS locations' 'ISS-Send-Locs rass'
#endif
		line
#ifdef notdef
		submenu 'VOR/DME' 'VORmenu'
		entry 'CLASS stations' 'put_component c_sounding_loc'
		entry 'NWS soundings' 'put_component c_nwssounding_loc'
		entry 'Profilers' 'put_component c_profiler_loc'
		line
		submenu 'VOR/DME Range Rings' VORRings 
#endif
		submenu 'Radar Range Rings' RadarRings
		entry 'X-Y Grid (km)' \
			'putc3 p_kmgrid x-spacing 300 y-spacing 300 color cyan'
		entry 'Lat/Lon Grid' \
			'putc3 p_llgrid x-spacing 300 y-spacing 300 color cyan'
		line
		entry 'Window Bounds' 'send-wbounds'
	endmenu
enddef


!-----------------------------------
! Customize the window template menu
!
require "cfg-tools"

define widget template-menu intmenu 'window templates'
	title 'Window Templates'
	line
	entry 'Constant altitude plot' \
		'create-window cap cap-template big'
	entry 'GOES-8 Satellite' 'create-window cap goes-template big'
	entry 'UAV Map' 'create-window cap uav-map big'
	entry 'Skew-t plot' \
		'create-window skewt skewt-template sounding'
	entry '915 MHz Wind profile' \
		'create-window wind-profile 915wind-template xyplot'
	entry '915 MHz Temperatures' \
		'create-window temp-profile 915temp-template xyplot'
	entry '50 MHz Wind profile' \
		'create-window wind-profile 50wind-template xyplot'
	entry '50 MHz Temperatures' \
		'create-window temp-profile 50temp-template xyplot'
	entry 'MFR Time Series' \
		'create-window tseries mfr-template xyplot'
	entry 'BLC Cloud Heights' \
		'create-window tseries blc-template xyplot'
	entry 'Time-series plot' \
		'create-window tseries tseries-template xyplot'
	entry 'Simple line plot' \
		'create-window lineplot lineplot-template xyplot'
#ifndef UAV
	entry 'Wind profile' 'create-window wind wind-template xyplot'
	entry 'RASS profile' 'create-window rass rass-template xyplot'
	entry 'XY Graph' 'create-window xygraph xygraph-template xyplot'
	entry 'Vertical cross-section' \
		'create-window xsect xsect-template default'
#endif
	entry 'Real-time clock' 'create-clock'
endmenu
!-------------------------------------


#ifndef UAV
define widget uav-config-menu intmenu 'UAV configurations'
	title 'UAV Configurations'
	line
	entry 'UDF Track' 'display uav-track' (dm$config = 'uav-track')
#ifdef notdef
	entry 'NGM Model' 'display NGM' (dm$config = 'NGM')
#endif
	entry '915 MHz Profiles' \
		'display Profiler915' (dm$config = 'Profiler915')
	entry '50 MHz Profiles' \
		'display Profiler50' (dm$config = 'Profiler50')
	entry 'NWS Surface Mesonet' 'display Mesonet' (dm$config = 'Mesonet')
endmenu
#endif

#ifdef notdef
define widget goes-7-menu intmenu 'GOES-7 images'
	title 'GOES-7 Images'
	line
	entry 'GOES-7 Visible' \
	   'putc2 p_satellite platform g7vismerc field vas_visible'
	entry 'GOES-7 Channel 5 brightness' \
	   'putc2 p_satellite platform g7irmerc field vas_ir5'
	entry 'GOES-7 Channel 8 brightness' \
	   'putc2 p_satellite platform g7ir8merc field vas_ir8'
	entry 'GOES-7 Channel 12 brightness' \
	   'putc2 p_satellite platform g7irmerc field vas_ir12'
	entry 'GOES-7 Channel 5 radiances' \
	   'putc2 p_satellite platform g7radirmerc field vas_ir5'
	entry 'GOES-7 Channel 8 radiances' \
	   'putc2 p_satellite platform g7radir8merc field vas_ir8'
	entry 'GOES-7 Channel 12 radiances' \
	   'putc2 p_satellite platform g7radirmerc field vas_ir12'
endmenu
#endif /* notdef */


!
! DataStore widget listings
!
define widget dslistings intmenu 'dsdwidget listings'
	title 'Data Store Widget Listings'
	line
	entry 'All Platforms' \
	   'shell "dsdwidget -a -t All\ Platforms &"'
#ifndef UAV
	entry 'EBBR Platforms' \
	   'shell "dsdwidget -a -t EBBR\ Platforms ebbr &"'
#endif
	entry 'SMOS and Tower' \
	   'shell "dsdwidget -a -t Surface\ and\ Tower smos twr21 &"'
	entry 'RASS Profiles' \
	   'shell "dsdwidget -a -t RASS\ Profiles rwpwind rwptemp &"'
	entry 'Soundings' \
	   'shell "dsdwidget -a -t Soundings sonde &"'
	entry 'MPL and BLC' \
	   'shell "dsdwidget -a -t MPL\ and\ BLC mpl blc &"'
	entry 'MFR and MFRSR' \
	   'shell "dsdwidget -a -t MFR\ and\ MFRSR mfr &"'
	entry 'SIROS Platforms' \
	   'shell "dsdwidget -a -t SIROS\ Platforms siros &"'
#ifndef UAV
	entry 'AERI' \
	   'shell "dsdwidget -a -t AERI\ Platforms aeri &"'
#endif
	entry 'MWR, WVR, and WSI' \
	   'shell "dsdwidget -a -t MWR,\ WVR,\ and\ WSI mwr wvr wsi &"'
	entry 'Mesonets' \
	   'shell "dsdwidget -a -t Mesonets mesoX sfchrlyX okmX nwssurf &"'
	entry 'Satellites' \
	   'shell "dsdwidget -a -t Satellites goes avhrr &"'
	entry 'Models' \
	   'shell "dsdwidget -a -t Models sgpngm250 sgpeta mm5ncar sgpruc &"'
	line
#ifndef UAV
	entry 'IDASS IOP Platforms' \
   'shell "dsdwidget -a -t NCAR\ IOP prof/ sounding/ surf/ wpdn mm5ncar &"'
	line
#endif
	entry 'Central Facility' \
   'shell "dsdwidget -a -t Central\ Facility\ Platforms C1 C2 CF E13 E14 &"'
	entry 'Boundary Facilities' \
	   'shell "dsdwidget -a -t Boundary\ Facilities B\[123456\] &"'
	entry 'Level a1 Platforms' \
	   'shell "dsdwidget -a -t Level\ a1\ Platforms \.a1\$ &"'
	entry 'Level a2 Platforms' \
	   'shell "dsdwidget -a -t Level\ a2\ Platforms \.a2\$ &"'
	entry 'Level c Platforms' \
	   'shell "dsdwidget -a -t Level\ c\ Platforms \.c\[012\]\$ &"'
endmenu


#ifndef UAV
define widget aeri-menu intmenu 'aeri platforms'
	title 'AERI Central Facility'
	line
	entry 'AERI Summary' \
	   'PutScalar sgpaerisummaryC1.a1 wave_num_avg_rad_675'
	entry 'AERI Line-by-Line Clouds' \
	   'PutScalar sgpaerilblcloudsC1.c1 mean_cloud1_cbh'
	entry 'AERI Channel 1' \
	   'PutScalar sgpaerich1C1.a1 hotBBTemp'
	entry 'AERI Channel 2' \
	   'PutScalar sgpaerich2C1.a1 hotBBTemp'
endmenu


define widget mfrsr-menu intmenu 'mfrsr'
	title 'MFRSR Plots'
	line
	entry 'MFRSR CAP plot' \
	   'putc2 p_station platform sgpmfrsrN1.a0 icon mfrsr'
	entry 'MFRSR Time Series' \
	   'PutScalar sgpmfrsrN1.a0/1 tot1'
endmenu
#endif


define widget mwr-cf-menu intmenu 'central facility mwr platforms'
	title 'MWR Central Facility'
	line
	entry 'Line-of-Sight (a1)' 'PutScalar sgpmwrlosC1.a1 vap'
#ifndef UAV
	entry 'Line-of-Sight (a0)' 'PutScalar sgpmwrlosC1.a0 vap'
	entry 'Line-of-Sight (b2)' 'PutScalar sgpmwrlosC1.b2 vap'
	entry '1-minute averages (c1)' 'PutScalar sgp1mwravgC1.c1 vap'
	entry '5-minute averages (c1)' 'PutScalar sgp5mwravgC1.c1 vap'
#endif
endmenu

#ifndef UAV
define widget mwr-b1-menu intmenu 'B1 mwr platforms'
	title 'MWR Boundary Facility One'
	line
	entry 'Line-of-Sight (a1)' 'PutScalar sgpmwrlosB1.a1 vap'
	entry '5-minute averages (c1)' 'PutScalar sgp5mwravgB1.c1 vap'
endmenu

define widget mwr-b4-menu intmenu 'B4 mwr platforms'
	title 'MWR Boundary Facility Four'
	line
	entry 'Line-of-Sight (a1)' 'PutScalar sgpmwrlosB4.a1 vap'
	entry '5-minute averages (c1)' 'PutScalar sgp5mwravgB4.c1 vap'
endmenu

define widget mwr-b5-menu intmenu 'B5 mwr platforms'
	title 'MWR Boundary Facility Five'
	line
	entry 'Line-of-Sight (a1)' 'PutScalar sgpmwrlosB5.a1 vap'
	entry '5-minute averages (c1)' 'PutScalar sgp5mwravgB5.c1 vap'
endmenu

define widget qmemwrcol-menu intmenu 'mwr column qme platforms'
	title 'MWR Column QMEs (c1)'
	line
	entry 'Central Facility' \
	   'PutScalar sgpqmemwrcolC1.c1 mean_vap_mwr'
	entry 'Boundary Facility One' \
	   'PutScalar sgpqmemwrcolB1.c1 mean_vap_mwr'
	entry 'Boundary Facility Four' \
	   'PutScalar sgpqmemwrcolB4.c1 mean_vap_mwr'
	entry 'Boundary Facility Five' \
	   'PutScalar sgpqmemwrcolB5.c1 mean_vap_mwr'
endmenu


define widget sondewndcalc-menu intmenu 'sonde wind calcs'
	title 'Sonde Wind Calculation'
	line
	entry 'C1 Wind Calc' \
		'PutScalar DsgpsondewndcalcC1.c1 pres'
	entry 'B1 Wind Calc' \
		'PutScalar DsgpsondewndcalcB1.c1 pres'
	entry 'B4 Wind Calc' \
		'PutScalar DsgpsondewndcalcB4.c1 pres'
	entry 'B5 Wind Calc' \
		'PutScalar DsgpsondewndcalcB5.c1 pres'
	entry 'B6 Wind Calc' \
		'PutScalar DsgpsondewndcalcB6.c1 pres'
endmenu
#endif /* ! UAV */

#ifdef notdef
define widget ngm-uav-menu intmenu 'ngm plots for the uav ngm platforms'
	title 'Nested Grid Model (UAV)'
	line
	entry 'Line Contours' \
		'putc1 p_uav_ngm representation "contour"' 
	entry 'Filled Contours' \
		'putc1 p_uav_ngm representation "filled-contour"' 
	entry 'Wind Vectors' \
		'sendout p_uav_ngm_vector pick'
endmenu
#endif


define widget siros intmenu 'siros'
	title 'SIROS Time Series'
	line
#ifndef UAV
	entry 'Central Facility (also E13, Lamont)' \
		'putc1 c_siros platform DsgpsirosE13.a1'
	entry 'Extended Facility E4' \
		'putc1 c_siros platform DsgpsirosE4.a1'
	entry 'Extended Facility E7' \
		'putc1 c_siros platform DsgpsirosE7.a1'
	entry 'Extended Facility E9 (also Ashton)' \
		'putc1 c_siros platform DsgpsirosE9.a1'
#endif
	entry 'Extended Facility E8' \
		'putc1 c_siros platform DsgpsirosE8.a1'
	entry 'Extended Facility E11' \
		'putc1 c_siros platform DsgpsirosE11.a1'
	entry 'Extended Facility E13' \
		'putc1 c_siros platform DsgpsirosE13.a1'
	entry 'Extended Facility E15 (also Ringwood)' \
		'putc1 c_siros platform DsgpsirosE15.a1'
	entry 'Extended Facility E16' \
		'putc1 c_siros platform DsgpsirosE16.a1'
endmenu


#ifndef UAV
define widget tower-menu intmenu 'tower platforms'
	title "Tower Platforms"
	line
	entry "1-minute (a0)" 'PutScalar Dsgp1twr21xC1.a0 temp'
	entry "1-minute (a1)" 'PutScalar Dsgp1twr21xC1.a1 temp'
	entry "30-minute (a0)" 'PutScalar Dsgp30twr21xC1.a0 temp'
	entry "30-minute (a1)" 'PutScalar Dsgp30twr21xC1.a1 temp'
	entry "Daily (a0)" 'PutScalar Dsgp1440twr21xC1.a0 temp'
endmenu
#endif


!----------------------------------------------------------------
! Mesonet submenus
!----------------------------------------------------------------

#ifndef UAV
define widget wpdn-menu intmenu 'wpdn plots'
	title 'Wind Profiler Demo Network'
	line
	entry 'Station Plot - Low Mode Winds' \
	   'putc2 p_wpdn_station u-field u_wind_low v-field v_wind_low'
	entry 'Station Plot - High Mode Winds' \
	   'putc2 p_wpdn_station u-field u_wind_hi v-field v_wind_hi'
	line
	entry 'Gridded Wind Vectors (Low Mode)' \
	   'putc2 p_wpdn_winds u-field u_wind_low v-field v_wind_low'
	entry 'Gridded Wind Vectors (Low Mode)' \
	   'putc2 p_wpdn_winds u-field u_wind_hi v-field v_wind_hi'
	line
	entry 'Consensus Contours - Low Mode' \
	   'putc1 p_wpdn_contour field cons_n_low'
	entry 'Consensus Contours - High Mode' \
	   'putc1 p_wpdn_contour field cons_n_hi'
endmenu
#endif

define widget smos-irgrid-menu intmenu 'smos irgrids'
	title 'SMOS Network Plots'
	line
	entry 'Station Plot' \
	   'putc3 p_station platform #smos_plats icon smos field temp'
	entry 'Contour Plot' \
	   'putc3 p_contour platform #smos_plats icon smos field temp'
	entry 'Gridded Wind Vectors' \
	   'putc2 p_irg_winds platform #smos_plats icon smos'
endmenu

#ifndef UAV
define widget ebbr-irgrid-menu intmenu 'ebbr irgrids'
	title 'EBBR Network Plots'
	line
	entry 'Station Plot' \
	   'putc3 p_station platform #ebbr_plats icon ebbr field pres'
	entry 'Contour Plot' \
	   'putc3 p_contour platform #ebbr_plats icon ebbr field pres'
	entry 'Gridded Wind Vectors' \
	   'putc2 p_irg_winds platform #ebbr_plats icon ebbr'
endmenu

define widget kansas-hourly intmenu 'kansas'
	title 'Kansas Hourly Mesonet'
	line
	entry 'Station Plot' \
	   'putc2 p_station platform sgpksuhrlymesoX1.b1 icon sfc_hourly'
	entry 'Contour Plot' \
	   'putc2 p_contour platform sgpksuhrlymesoX1.b1 icon grid_hourly'
	entry 'Gridded Wind Vectors' \
   'putc2 p_irg_winds platform sgpksuhrlymesoX1.b1 icon grid_hourly_vectors'
endmenu

define widget kansas-daily intmenu 'kansas'
	title 'Kansas Daily Mesonet'
	line
	entry 'Station Plot' \
	   'putc2 p_station platform sgpksudlymesoX1.b1 icon meso_stations'
	entry 'Contour Plot' \
	   'putc2 p_contour platform sgpksudlymesoX1.b1 icon mesonet'
	entry 'Gridded Wind Vectors' \
	   'putc2 p_irg_winds platform sgpksudlymesoX1.b1 icon meso_winds'
endmenu

define widget oklahoma05a0 intmenu 'oklahoma'
	title 'Oklahoma Mesonet 5-minute (a0)'
	line
	entry 'Station Plot' \
	   'putc2 p_station platform sgp05okmX1.a0 icon sfc_5min'
	entry 'Contour Plot' \
	   'putc2 p_contour platform sgp05okmX1.a0 icon grid_5min'
	entry 'Gridded Wind Vectors' \
	   'putc2 p_irg_winds platform sgp05okmX1.a0 icon grid_5min_vectors'
endmenu

define widget oklahoma05a1 intmenu 'oklahoma'
	title 'Oklahoma Mesonet 5-minute (a1)'
	line
	entry 'Station Plot' \
	   'putc2 p_station platform sgp05okmX1.a1 icon sfc_5min'
	entry 'Contour Plot' \
	   'putc2 p_contour platform sgp05okmX1.a1 icon grid_5min'
	entry 'Gridded Wind Vectors' \
	   'putc2 p_irg_winds platform sgp05okmX1.a1 icon grid_5min_vectors'
endmenu

define widget oklahoma15a1 intmenu 'oklahoma'
	title 'Oklahoma Mesonet 15-minute (a1)'
	line
	entry 'Station Plot' \
	   'putc2 p_station platform sgp15okmX1.a1 icon meso_stations'
	entry 'Contour Plot' \
	   'putc2 p_contour platform sgp15okmX1.a1 icon mesonet'
	entry 'Gridded Wind Vectors' \
	   'putc2 p_irg_winds platform sgp15okmX1.a1 icon meso_winds'
endmenu

define widget oklahoma15a0 intmenu 'oklahoma'
	title 'Oklahoma Mesonet 15-minute (a0)'
	line
	entry 'Station Plot' \
	   'putc2 p_station platform sgp15okmX1.a0 icon meso_stations'
	entry 'Contour Plot' \
	   'putc2 p_contour platform sgp15okmX1.a0 icon mesonet'
	entry 'Gridded Wind Vectors' \
	   'putc2 p_irg_winds platform sgp15okmX1.a0 icon meso_winds'
endmenu
#endif /* ! UAV */

define widget nwssurf intmenu 'nws surface mesonet'
	title 'NWS Surface Mesonet'
	line
	entry 'Station Plot' 'sendout p_nws_station pick'
	entry 'Contour Plot' 'putc1 p_nws_contour representation contour'
	entry 'Gridded Wind Vectors' \
   'putc2 p_irg_winds platform sgpnwssurfX1.a1 icon meso_winds'
endmenu

#ifdef notdef /* replaced by nwssurfX1.a1 */
define widget nwssfchrly intmenu 'nws surface hourlies'
	title 'NWS Hourly Surface Data'
	line
	entry 'Station Plot' 'sendout p_nws_station pick'
	entry 'Contour Plot' 'putc1 p_nws_contour representation contour'
	entry 'Gridded Wind Vectors' \
   'putc2 p_irg_winds platform sgpsfchrlyX1.a1 icon grid_hourly_vectors'
endmenu
#endif

#ifdef notdef
!
! Make these irgrid mesonets containing the given platform for all
! of the facilities which possess that platform
!
define widget facnet intmenu 'facility mesonet'
	title 'Facility Mesonet by Instrument'
	line
	entry 'SMOS 30-minute' 'beep'
	entry 'SMOS 1-minute' 'beep'
	entry 'EBBR' 'beep'
endmenu

define widget siros_facilities intmenu 'Siros Facilities'
	title 'siros facilities'
	line
	entry 'Central Facility (also E13, Lamont)' 'put_component c_CF_siros'
	entry 'Extended Facility E9 (also Ashton)' 'put_component c_E9_siros'
	entry 'Extended Facility E15 (also Ringwood)' 'put_component c_E15_siros'
endmenu

#endif /* notdef */

!
! Radar range ring menu.
!
define widget RadarRings intmenu 'radar range rings'
	title 'Radar Range Rings'
	line
	entry 'CP3 Range Rings' 'putc1 p_rings platform cp3'
	entry 'CP4 Range Rings' 'putc1 p_rings platform cp4'
	entry 'MHR Range Rings' 'putc1 p_rings platform mhr'
	entry 'OKC Range Rings' 'putc1 p_rings platform okc'
	entry 'FDR Range Rings' 'putc1 p_rings platform fdr'
	entry 'CIM Range Rings' 'putc1 p_rings platform cim'
	entry 'HOT Range Rings' 'putc1 p_rings platform hot'
	entry 'CHILL Range Rings' 'putc1 p_rings platform chill'
endmenu

