#!/bin/csh
#
# The COARE project startup file, to be run out of "startzeb".  Nothing too
# special here.
#

#
# Provide a reasonable default config and that's it.
#
if ( ! $?DEFAULT_CONFIG ) setenv DEFAULT_CONFIG wide
if ( ! $?INITIAL_TIME ) setenv INITIAL_TIME 1-dec-92
