#!/bin/csh
#
# The COARE project startup file, to be run out of "startzeb".  Nothing too
# special here.
#

#
# For historical reasons, we need a coare.map, but it's the same map as
# default.map...
#
(cd maps; ln -sf default.map coare.map)

#
# Provide a reasonable default config and that's it.
#
if ( ! $?DEFAULT_CONFIG ) setenv DEFAULT_CONFIG wide
if ( ! $?INITIAL_TIME ) setenv INITIAL_TIME 1-dec-92
if ( ! $?ZEBRA_CACHEDIR ) setenv ZEBRA_CACHEDIR $cwd/tmp
