#! /bin/sh
#
# $Id: makelinks,v 1.2 1999-04-13 21:51:37 granger Exp $
#
# Make some file links required in this project directory tree
#

exec <<EOTABLE
maps/default.map sgp.map
SGP .
dmmodules/cf-active-loc modules/cf-active-loc
dmmodules/ef-active-loc modules/ef-active-loc
EOTABLE

while read target src; do

	: echo "$target --> $src"
	if [ -h $target ]; then
		: echo "Link $target exists."
	else
		if [ -f $target ]; then
			echo "File $target in the way!"
		else
			(set -x; ln -s $src $target)
		fi
	fi

done


