#!/bin/csh -f
#
# Environment variable settings specific to ARM
#

echo "Reading proj_env"

setenv ZEBHOME $ZEB_TOPDIR
setenv HOST `uname -n`
if ($HOST == narnia) then
	setenv CONFIGHOME /scr/steam/arm/ARESE
	setenv DATAHOME /dt/granger/uav
#	setenv DATAHOME /scr/narnia/arm/data
else
	setenv CONFIGHOME /apps/development/ARESE
	setenv DATAHOME /apps/data
endif

# This is mostly to keep zstart quiet; DATAHOME will take precedence
# in ds.config
#
setenv DATA_DIR $DATAHOME/sgp/platforms

# Force multiple option on dm command line
#
#setenv ZEB_DM_CONFIG '-multiple dm.config'

