#!/bin/tcsh
#
# Set up environment for SPOL operations.
#
if (! $?DATA_DIR) setenv DATA_DIR /scr/data/spol
if (! $?ZEB_TOPDIR) setenv ZEB_TOPDIR /zebra
if (! $?ZEB_EVENTLOGGER) \
    setenv ZEB_EVENTLOGGER "$ZEB_TOPDIR/bin/EventLogger -w"
if (! $?DEFAULT_CONFIG) setenv DEFAULT_CONFIG empty


# definitions for zplotd


setenv PROJECT_NAME IMPROVE2

setenv ZEB_CACHEDIR tmp
if (! $?ZEB_PROJDIR) setenv ZEB_PROJDIR /usr/local/zebra/project/improve2 
# Any displays started on this project should leave the datastore
# running in the background for other displays and for the plot
# generation.
setenv PRESERVE_ZEB 1

# This project uses its own specific socket
#setenv ZEB_SOCKET "/tmp/zebra.improve2"

# The spool dir is where images are dumped by batch-plot
setenv BATCH_IMAGE_SPOOL /scr/data/zebra_images

# Use a fixed zebra top since we are version-dependent
setenv ZEB_TOPDIR /zebra

# Settings required for ftpplots
#setenv PLOT_FTP_HOST "ftp.joss.ucar.edu"
#setenv PLOT_FTP_DIR "/pub/incoming/catalog/cases99"
setenv PLOT_FTP_ENABLE 0

# Special paths for Xvfb and zebra.
setenv PATH "$ZEB_TOPDIR/bin:/local/X11R6/bin:$PATH"
if ($?LD_LIBRARY_PATH) then
    setenv LD_LIBRARY_PATH "/local/X11R6/lib:/usr/local/lib:${LD_LIBRARY_PATH}"
else
    setenv LD_LIBRARY_PATH "/local/X11R6/lib:/usr/local/lib"
endif

# zplotd parameters
setenv IMAGE_MAIL_LIST " vanandel "
#setenv PLOT_PLATFORMS "$ZEB_PROJDIR/Plots"

# These are the hours each day at which we want plots, 
# and the length of the plot period
setenv PLOT_HOURS "10 22"
setenv PLOT_PERIOD 12

