#!/bin/csh
#
# The TRMM project startup file, to be run out of "startzeb".  Nothing too
# special here.
#

#
# Provide a reasonable default config and that's it.
#
if ( ! $?DEFAULT_CONFIG ) setenv DEFAULT_CONFIG xsect
