#ifndef	graph_HEADER
#define	graph_HEADER

/*
 * graph_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `graph.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	window1;
	Xv_opaque	canvas1;
} graph_window1_objects;

extern graph_window1_objects	*graph_window1_objects_initialize();

extern Xv_opaque	graph_window1_window1_create();
extern Xv_opaque	graph_window1_canvas1_create();
#endif
