/*
 * graph_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `graph.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/icon_load.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include <gcm.h>
#include "graph_ui.h"

/*
 * Initialize an instance of object `window1'.
 */
graph_window1_objects *
graph_window1_objects_initialize(ip, owner)
	graph_window1_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (graph_window1_objects *) calloc(1, sizeof (graph_window1_objects))))
		return (graph_window1_objects *) NULL;
	if (!ip->window1)
		ip->window1 = graph_window1_window1_create(ip, owner);
	if (!ip->canvas1)
		ip->canvas1 = graph_window1_canvas1_create(ip, ip->window1);
	return ip;
}

/*
 * Create object `window1' in the specified instance.

 */
Xv_opaque
graph_window1_window1_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 663,
		XV_HEIGHT, 449,
		XV_LABEL, "Base Window",
		FRAME_CLOSED, FALSE,
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `canvas1' in the specified instance.

 */
Xv_opaque
graph_window1_canvas1_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern Notify_value	event();
	extern void	repaint();
	Xv_opaque	obj;
	
	obj = xv_create(owner, CANVAS,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		CANVAS_REPAINT_PROC, repaint,
		CANVAS_X_PAINT_WINDOW, TRUE,
		NULL);
	gcm_initialize_colors(obj, "Dark Slate Blue", "Cyan");
	xv_set(canvas_paint_window(obj), WIN_CONSUME_EVENTS,
		WIN_MOUSE_BUTTONS,
		LOC_DRAG,
		NULL, NULL);
	notify_interpose_event_func(canvas_paint_window(obj),
		(Notify_func) event, NOTIFY_SAFE);
	xv_set(canvas_paint_window(obj), XV_KEY_DATA, INSTANCE, ip, NULL);
	return obj;
}

